// Generates src/assets/art.ts — the Vite replacement for source/build.py's
// DATA payload. Move data (M) is inlined as JSON; every sprite becomes an
// `import url from '<path>'` so Vite emits hashed, cacheable files instead of
// base64-in-HTML. Key space is identical to build.py so game code lookups
// (DATA.img['bram_holt/idle'], 'arena/aud01_a', 'vfx/slash', 'tile/...',
// 'prop/...', 'foe/...', 'shadow') keep working unchanged.
import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { join, basename, extname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..');
const ART_TS = join(ROOT, 'src', 'assets', 'art.ts');

const d = JSON.parse(readFileSync(join(ROOT, 'veilspire_iso', 'veilspire_iso.json'), 'utf8'));
const ch = d.characters;
const M = {
  animations: d.animations,
  characters: ch.map((c) => ({
    id: c.id, name: c.name, weapon: c.weapon, role: c.role, title: c.title, attacks: c.attacks,
  })),
};

// [manifest key, repo-relative file]
const files = [];
files.push(['shadow', 'veilspire_iso/shadow_standard.png']);
for (const c of ch) {
  const id = c.id;
  for (const a of Object.keys(c.sheets)) {
    files.push([`${id}/${a}`, `veilspire_iso/${id}/${a}.png`]);
    for (const p of ['p16', 'p38']) {
      const q = `veilspire_iso/${id}/${p}/${a}.png`;
      if (existsSync(join(ROOT, q))) files.push([`${id}/${p}/${a}`, q]);
    }
  }
}
const globDir = (dir, prefix) => {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return;
  for (const f of readdirSync(abs).sort()) {
    if (extname(f).toLowerCase() !== '.png') continue;
    files.push([prefix + basename(f, '.png'), join(dir, f)]);
  }
};
globDir('veilspire_iso/arena', 'arena/');
globDir('veilspire_iso/vfx', 'vfx/');
globDir('source/art/tiles', 'tile/');
globDir('source/art/props', 'prop/');
globDir('source/art/foes', 'foe/');

// Verify every referenced file exists (fail loud, like build.py would).
const missing = files.filter(([, f]) => !existsSync(join(ROOT, f)));
if (missing.length) {
  console.error('manifest: missing files:\n' + missing.map(([, f]) => '  ' + f).join('\n'));
  process.exit(1);
}

const seen = new Set();
for (const [k] of files) {
  if (seen.has(k)) { console.error(`manifest: duplicate key ${k}`); process.exit(1); }
  seen.add(k);
}

const toImportPath = (repoPath) => './' + relative(join(ROOT, 'src', 'assets'), join(ROOT, repoPath)).split(sep).join('/');
let out = `// GENERATED by scripts/manifest.mjs — do not edit.\n`;
files.forEach(([, f], i) => { out += `import url_${i} from '${toImportPath(f)}';\n`; });
out += `\nexport const M = ${JSON.stringify(M)};\n`;
out += `\nexport const img: Record<string, string> = {\n`;
files.forEach(([k], i) => { out += `  ${JSON.stringify(k)}: url_${i},\n`; });
out += `};\n`;
out += `\nexport const DATA = { M, img };\nexport type GameData = typeof DATA;\n`;

mkdirSync(join(ROOT, 'src', 'assets'), { recursive: true });
writeFileSync(ART_TS, out);
console.log(`manifest: ${files.length} sprites -> src/assets/art.ts`);
